trainer:
  ckpt_path: null
  gpus: 1
  max_epochs: 10
  seed: 42

model:
  base_learning_rate: 4.5e-6
  target: echo_diffusion.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 64
    lossconfig:
      target: echo_diffusion.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5
        perceptual_weight: 0


    ddconfig:
      double_z: True
      z_channels: 32
      resolution: -999
      in_channels: 3
      out_ch: 3
      ch: 8
      ch_mult: [ 1,2,4,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [] #[16,8]
      dropout: 0.0

data:
  batch_size: 8
  num_workers: 4
  wrap: True
  train:
    target: echo_diffusion.data.EchoDataset
    params:
      data_dir: /home/jovyan/data/camus_cityscape_format/train/images/
      img_size: 128
  validation:
    target: echo_diffusion.data.EchoDataset
    params:
      data_dir: /home/jovyan/data/camus_cityscape_format/test/images/
      img_size: 128


