trainer:
  ckpt_path: null
  gpus: 1
  max_epochs: 10
  seed: 42

model:
  base_learning_rate: 4.5e-6
  target: echo_diffusion.models.vae.EchoVAE
  params:
    loss_params:
      cross_entropy_weight: 0.1
      dice_weight: 1
      clip_weight: 1
      reconstruction_weight: 1
      kl_weight: 0.5

    encoder_img_params:
      image_size: 128
      in_channels: 3
      blocks: 6
      init_channels: 48
      latent_dim: 64
      use_batchnorm: True
      output_distribution: False

    decoder_img_params:
      image_size: 128
      out_channels: 3
      blocks: 6
      init_channels: 48
      latent_dim: 64

    encoder_seg_params:
      image_size: 128
      in_channels: 4
      blocks: 4
      init_channels: 48
      latent_dim: 16
      use_batchnorm: True
      output_distribution: False

    decoder_seg_params:
      image_size: 128
      out_channels: 4
      blocks: 4
      init_channels: 48
      latent_dim: 16


data:
  batch_size: 8
  num_workers: 4
  wrap: True
  train:
    target: echo_diffusion.data.EchoDataset
    params:
      data_dir: /home/jovyan/data/camus_cityscape_format/train/images/
      img_size: 256
  validation:
    target: echo_diffusion.data.EchoDataset
    params:
      data_dir: /home/jovyan/data/camus_cityscape_format/test/images/
      img_size: 256
